#!/var/vcap/packages/bash-4.3/bin/bash

fail() { 
  echo "$*" >&2 
  exit 1 
}

user() {
  local _action=$1 ; shift
  case ${_action} in
    (exec)  exec chpst -u "${userName}:${groupName}" "$@" ;;
    (run)   chpst -u "${userName}:${groupName}" "$@"      ;;
    (chown) chown -R "${userName}:${groupName}" "$@"      ;;
  esac
}

set_pid() {
  pid=0
  if [[ -s ${pidFile} ]]
  then pid=$(head -1 ${pidFile})
  fi
}

send_signal() { 
  set_pid
  if (( ${pid:-0} > 0 ))
  then kill -${1} ${pid}
  fi
}

turn_debugging_on() {
  echo "Turning Debugging On"
  export PS4='+(${BASH_SOURCE}:${LINENO})> ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  export DEBUG="true" 
  set -x
}

add_packages_to_path() { # Add all packages' /bin & /sbin into $PATH
  for _path in $(ls -d /var/vcap/packages/*/*bin)
  do PATH="${_path}:${PATH}"
  done ; export PATH
}

configure_job_paths() {
  paths=(
    "${jobPath}"
    "${runPath}"
    "${logPath}"
    "${tmpPath}"
    "${storePath}"
  )
  if (( ${UID} == 0 ))
  then
    for _path in "${paths[@]}"
    do
      [[ -d ${_path} ]] || mkdir -p "${_path}"
      chown -R ${userName}:${groupName} "${_path}"
      chmod 0775 "${_path}"
    done
  fi
}

ensure_consul_is_available() {
  while [[ -z $(curl -s http://127.0.0.1:8500/v1/status/leader | tr -d '"') ]]
  do sleep 5
  done
}

ensure_postgres_user_exists() {
  # Wait until we can connect to PostgreSQL...
  while ! psql --port ${RDPGD_PG_PORT} -U vcap postgres -t -c "SELECT CURRENT_TIMESTAMP;"
  do sleep 2
  done

  if [[ -z $(psql --port ${RDPGD_PG_PORT} -U vcap postgres -t -c "SELECT rolname FROM pg_roles WHERE rolname='postgres';" 2>/dev/null) ]]
  then # Create the rdpg User
    psql --port ${RDPGD_PG_PORT} -U vcap postgres \
      -c "CREATE USER postgres WITH SUPERUSER CREATEDB CREATEROLE INHERIT;" || true

    psql --port ${RDPGD_PG_PORT} -U vcap postgres \
      -c "ALTER USER postgres ENCRYPTED PASSWORD '${RDPGD_PG_PASS}';" || true
  fi
}

configure_pgbouncer() {
  if ! grep -q rdpg /var/vcap/store/pgbouncer/config/users 
  then
    while ! [[ -d /var/vcap/store/pgbouncer/config ]]
    do sleep 1
    done
    cp ${jobPath}/config/pgbouncer/* /var/vcap/store/pgbouncer/config/
    /var/vcap/jobs/pgbouncer/bin/control reload
  fi
}
