#!/usr/bin/env bash

fail() { echo $* ; exit 1 ; }

dev_release() {
  go get -u github.com/laher/goxc
  go get -u github.com/aktau/github-release
  $GOPATH/bin/goxc -pv ${version}
  echo "Release Archive Generated: .releases/${version}/rdpgd_${version}_linux_amd64.tar.gz"
}

final_release() {
  set -v
  set -x 
  if [[ -z ${GITHUB_TOKEN} ]]
  then fail "GITHUB_TOKEN is not set in the environment: https://help.github.com/articles/creating-an-access-token-for-command-line-use/"
  fi

  go get -u github.com/laher/goxc
  go get -u github.com/aktau/github-release

  $GOPATH/bin/goxc -pv ${version}
  releaseMsg="RDPG Daemon (rdpgd) Release ${version}"
  git tag -a ${version} -m "${releaseMsg}"
  for remote in $(git remote)
  do git push ${remote} --tags || true
  done

  $GOPATH/bin/github-release release \
    --user starkandwayne \
    --repo rdpgd \
    --tag ${version} \
    --name "RDPG Daemon (rdpgd) Release ${version}" \
    --description "RDPG Agent to run with the RDPG BOSH Release: https://github.com/starkandwayne/rdpg-boshrelease"

  $GOPATH/bin/github-release upload \
    --user starkandwayne \
    --repo rdpgd \
    --tag ${version} \
    --name "rdpgd_${version}_linux_amd64.tar.gz" \
    --file "./.releases/${version}/rdpgd_${version}_linux_amd64.tar.gz"
}

get_catalog() {
  curl ${1:-} -s -X GET -H "X-Broker-API-Version: 2.4" -H "Content-Type: application/json" \
    http://cfadmin:cfadmin@10.244.2.2:8888/v2/catalog
  echo
}

export \
  RDPGD_LOG_LEVEL=trace \
  RDPGD_SB_PORT=8888 \
  RDPGD_SB_USER=cfadmin \
  RDPGD_SB_PASS=cfadmin \
  RDPGD_ADMIN_PORT=58888 \
  RDPGD_POOL_SIZE=10 \
  RDPGD_ADMIN_PG_URI="postgresql://postgres:admin@10.244.2.2:7432/rdpg?sslmode=disable&connect_timeout=5&fallback_application_name=rdpgd" \
  RDPGD_SERVICE_DNS="10.244.2.2:8888"

action=$1
shift || echo "No action given!!"

instanceId="$(uuidgen)"
serviceId="$(uuidgen)"
planId="$(uuidgen)"
organizationId="$(uuidgen)"
spaceId="$(uuidgen)"
bindingId="$(uuidgen)"
appId="$(uuidgen)"
if [[ ${DEBUG:-} == "true" ]] ; then set -x ; fi 

case ${action} in
  (run)
    exec go run rdpgd.go
    ;;
  (tunnel)
    echo "Password when prompted: c1oudc0w"
    exec ssh  -L 55432:127.0.0.1:7432 vcap@10.244.2.2
    ;;
  (test)
    exec go test
    ;;
  (convey)
    export RDPGD_LOG_LEVEL=error
    export GOPATH="$PWD/Godeps/_workspace"
    mkdir -p ${GOPATH}/src/github.com/starkandwayne
    if ! [[ -L ${GOPATH}/src/github.com/starkandwayne/rdpgd ]]
    then ln -sf ${PWD} ${GOPATH}/src/github.com/starkandwayne/rdpgd
    fi
    go get -u github.com/smartystreets/goconvey
    exec $GOPATH/bin/goconvey
    ;;
  (catalog)
    get_catalog -v
    echo
  ;;
  (provision)
    cl="$(get_catalog | tr -d '"' | tr ',' ' ' | sed -e 's%:\[{%_%g')"
    planId=$( echo "${cl}" | awk -F: '/plans_id/{print $2}' | awk '{print $1}')
    serviceId=$( echo "${cl}" | awk -F: '/services_id/{print $2}')
    echo "instanceId=${instanceId}"
    set -v -x
    curl -v -s -X PUT -H "X-Broker-API-Version: 2.4" -H "Content-Type: application/json" \
      "http://cfadmin:cfadmin@10.244.2.2:8888/v2/service_instances/${instanceId}" \
      -d "{ \"service_id\": \"${serviceId}\", \"plan_id\": \"${planId}\", \"organization_guid\": \"${organizationId}\", \"space_guid\": \"${spaceId}\" }"
    echo
    ;;
  (bind)
    instanceId=$1
    if [[ -z ${instanceId} ]] ; then fail "Please specify an InstanceID!" ; fi
    set -x -v
    curl -v -X PUT -H "X-Broker-API-Version: 2.4" -H "Content-Type: application/json" \
      "http://cfadmin:cfadmin@10.244.2.2:8888/v2/service_instances/${instanceId}/service_bindings/${bindingId}" \
      -d "{ \"service_id\": \"${serviceId}\", \"plan_id\": \"${planId}\", \"app_guid\": \"${appId}\"}"
    echo
    ;;
  (unbind)
    instanceId=$1
    bindingId=$2
    if [[ -z ${instanceId} ]] ; then fail "Please specify an InstanceID!" ; fi
    if [[ -z ${bindingId} ]] ; then fail "Please specify a BindingID!" ; fi
    curl -v -X DELETE -H "X-Broker-API-Version: 2.4" -H "Content-Type: application/json" \
      "http://cfadmin:cfadmin@10.244.2.2:8888/v2/service_instances/${instanceId}/service_bindings/${bindingId}"
    echo
    ;;
  (deprovision)
    id=$1
    if [[ -z ${instanceId} ]] ; then fail "Please specify an InstanceID!" ; fi
    curl -X DELETE -H "X-Broker-API-Version: 2.4" -v \
      "http://cfadmin:cfadmin@10.244.2.2:8888/v2/service_instances/${id}"
    echo
    ;;
  (dev_release)
    version="$1"
    if [[ -z ${version} ]]
    then fail "A version must be given for the release."
    fi
    dev_release
    ;;
  (final_release)
    version="$1"
    if [[ -z ${version} ]]
    then fail "A version must be given for the release."
    fi
    final_release
    ;;
  (cf_integration_test)
    set -v
    cf create-service-broker rdpg cfadmin cfadmin http://${RDPGD_SERVICE_DNS}
    cf enable-service-access rdpg -o $USER
    cf marketplace
    cf create-service rdpg shared rdpg-service-1
    cf services
    cf bind-service rdpg-cf-service-checks rdpg-service-1
    cf restage rdpg-cf-service-checks
    cf unbind-service rdpg-cf-service-checks rdpg-service-1
    cf delete-service rdpg-service-1
    set +v
    ;;
esac
